OreumOreum/OREUM_BE

- src/main/java/com/zzarit/oreum/folder/controller/FolderController.java
- src/main/java/com/zzarit/oreum/folder/domain/Folder.java
- src/main/java/com/zzarit/oreum/folder/domain/repository/FolderRepository.java
- src/main/java/com/zzarit/oreum/folder/service/FolderService.java
- src/main/java/com/zzarit/oreum/folder/service/dto/FolderIdListDto.java
- src/main/java/com/zzarit/oreum/folder/service/dto/FolderNameDto.java
- src/main/java/com/zzarit/oreum/folder/service/dto/FolderResponseDto.java
> [feat] 폴더 삭제 Api 구현

- src/main/java/com/zzarit/oreum/folder/controller/FolderController.java
- src/main/java/com/zzarit/oreum/folder/domain/repository/FolderRepository.java
- src/main/java/com/zzarit/oreum/folder/service/FolderService.java
- src/main/java/com/zzarit/oreum/folder/service/dto/FolderDetailResponseDto.java
- src/main/java/com/zzarit/oreum/folder/service/dto/FolderIdListRequestDto.java
- src/main/java/com/zzarit/oreum/folder/service/dto/FolderNameDto.java
- src/main/java/com/zzarit/oreum/folder/service/dto/FolderNameRequestDto.java
- src/main/java/com/zzarit/oreum/folder/service/dto/FolderPlaceRequestDto.java
- src/main/resources/data.sql
> [feat] 폴더 장소 추가 Api 구현

- src/main/java/com/zzarit/oreum/folder/controller/FolderController.java
- src/main/java/com/zzarit/oreum/folder/domain/repository/FolderPlaceRepository.java
- src/main/java/com/zzarit/oreum/folder/service/FolderPlaceService.java
- src/main/java/com/zzarit/oreum/folder/service/FolderService.java
- src/main/java/com/zzarit/oreum/folder/service/dto/FolderPlaceListRequestDto.java
> [feat] 폴더 장소 삭제 Api 구현

- src/main/java/com/zzarit/oreum/folder/controller/FolderController.java
- src/main/java/com/zzarit/oreum/folder/service/FolderPlaceService.java
- src/main/java/com/zzarit/oreum/folder/service/dto/FolderDetailResponseDto.java
- src/main/java/com/zzarit/oreum/folder/service/dto/FolderPlaceResponseDto.java
> [feat] 폴더 장소 불러오기 Api 구현

- src/main/java/com/zzarit/oreum/planner/controller/PlannerController.java
- src/main/java/com/zzarit/oreum/planner/domain/PlannerPlace.java
- src/main/java/com/zzarit/oreum/planner/service/PlannerService.java
- src/main/java/com/zzarit/oreum/planner/service/dto/PlannerCreateRequestDto.java
- src/main/java/com/zzarit/oreum/planner/service/dto/PlannerPlaceRequestDto.java
> [feat] 여행 계획 생성 Api 구현

- src/main/java/com/zzarit/oreum/folder/controller/FolderController.java
- src/main/java/com/zzarit/oreum/folder/service/FolderService.java
- src/main/java/com/zzarit/oreum/planner/controller/PlannerController.java
- src/main/java/com/zzarit/oreum/planner/domain/Planner.java
- src/main/java/com/zzarit/oreum/planner/domain/repository/PlannerRepository.java
- src/main/java/com/zzarit/oreum/planner/service/PlannerService.java
- src/main/java/com/zzarit/oreum/planner/service/dto/PlannerIdListRequestDto.java
> Feature/#24 여행 계획 삭제 Api 구현

- src/main/java/com/zzarit/oreum/planner/controller/PlannerController.java
- src/main/java/com/zzarit/oreum/planner/domain/repository/PlannerRepository.java
- src/main/java/com/zzarit/oreum/planner/service/PlannerService.java
- src/main/java/com/zzarit/oreum/planner/service/dto/PlannerPlaceResponseDto.java
> [feat] 여행 계획 장소 불러오기 Api 구현

- src/main/java/com/zzarit/oreum/folder/domain/Folder.java
- src/main/java/com/zzarit/oreum/member/domain/Member.java
- src/main/java/com/zzarit/oreum/place/controller/PlaceController.java
- src/main/java/com/zzarit/oreum/place/domain/Course.java
- src/main/java/com/zzarit/oreum/place/domain/Rating.java
- src/main/java/com/zzarit/oreum/place/domain/Review.java
- src/main/java/com/zzarit/oreum/place/domain/repository/RatingRepository.java
- src/main/java/com/zzarit/oreum/place/domain/repository/ReviewRepository.java
- src/main/java/com/zzarit/oreum/place/service/PlaceService.java
- src/main/java/com/zzarit/oreum/place/service/dto/ReviewCreateRequestDto.java
- src/main/resources/data.sql
- src/test/java/com/zzarit/oreum/auth/service/AuthServiceTest.java
- src/test/java/com/zzarit/oreum/place/controller/PlaceControllerTest.java
- src/test/java/com/zzarit/oreum/place/service/PlaceServiceTest.java
> [feat] 리뷰, 별점 작성 기능

- .github/workflows/ci-cd.yml
> [fix] ci-cd.yml 수정

- .github/workflows/ci-cd.yml
- src/main/java/com/zzarit/oreum/folder/domain/Folder.java
- src/main/java/com/zzarit/oreum/folder/domain/repository/FolderRepository.java
- src/main/java/com/zzarit/oreum/folder/service/FolderPlaceService.java
- src/main/resources/application.yml
- src/main/resources/data.sql
> [fix] 기본폴더 컬럼 추가

- src/main/java/com/zzarit/oreum/folder/domain/repository/FolderRepository.java
- src/main/java/com/zzarit/oreum/folder/service/dto/FolderPlaceResponseDto.java
- src/main/java/com/zzarit/oreum/folder/service/dto/FolderResponseDto.java
> [fix] 폴더 조회 API 수정

- src/main/java/com/zzarit/oreum/folder/service/FolderPlaceService.java
> [fix] 폴더 상세조회 API 수정

- src/main/java/com/zzarit/oreum/place/service/dto/CourseDetailResponseDto.java
- src/main/resources/data.sql
> [fix] 코스 상세보기 수정 API

- src/main/java/com/zzarit/oreum/folder/service/dto/FolderResponseDto.java
> [fix] 폴더 조회: 빈배열 -> null

- src/main/java/com/zzarit/oreum/folder/service/dto/FolderResponseDto.java
> [fix] 폴더 조회: null값만 있을떄 제거

- src/main/java/com/zzarit/oreum/member/controller/MemberController.java
- src/main/java/com/zzarit/oreum/spot/controller/SpotController.java
> [fix] prefix 변경

- .github/workflows/ci-cd.yml
> [fix] CICD 파이프라인 수정

- .github/workflows/ci-cd.yml
> [fix] CICD 오류 수정

- src/main/java/com/zzarit/oreum/auth/service/OAuthClientComposite.java
- src/main/java/com/zzarit/oreum/auth/service/client/AppleClient.java
- src/main/java/com/zzarit/oreum/scheduler/service/SynchronizeService.java
> [fix] APPLE로그인 수정

- src/main/java/com/zzarit/oreum/auth/service/OAuthClientComposite.java
- src/main/java/com/zzarit/oreum/spot/controller/SpotController.java
- src/main/java/com/zzarit/oreum/spot/service/SpotService.java
- src/main/java/com/zzarit/oreum/spot/service/dto/MonthlySpotResponseDto.java
- src/main/resources/data.sql
> [fix] 이달의여행지 조회: 같은 유형 방문자수 추가

- src/main/java/com/zzarit/oreum/folder/domain/repository/FolderRepository.java
- src/main/resources/data.sql
> [fix] 폴더- createdAt ASC 정렬

- src/main/java/com/zzarit/oreum/place/service/dto/CourseDetailResponseDto.java
- src/main/java/com/zzarit/oreum/place/service/dto/CourseResponseDto.java
> [feat] 코스 리스트에 contentID 추가

- src/main/java/com/zzarit/oreum/folder/service/dto/FolderPlaceResponseDto.java
- src/main/java/com/zzarit/oreum/place/service/dto/PlaceDto.java
- src/main/java/com/zzarit/oreum/planner/service/dto/PlannerPlaceResponseDto.java
> [fix] dto 수정: contentID 추가

- src/main/java/com/zzarit/oreum/global/util/OreumStringUtils.java
- src/main/java/com/zzarit/oreum/place/domain/repository/CourseRepository.java
- src/main/java/com/zzarit/oreum/place/domain/repository/PlaceRepository.java
- src/main/java/com/zzarit/oreum/scheduler/client/OpenApiClient.java
- src/main/java/com/zzarit/oreum/scheduler/client/dto/SynctDto.java
- src/main/java/com/zzarit/oreum/scheduler/service/DailySynchronizeService.java
- src/main/java/com/zzarit/oreum/scheduler/service/DaySynchronizeService.java
- src/main/java/com/zzarit/oreum/scheduler/service/MonthlyBatchService.java
- src/main/java/com/zzarit/oreum/scheduler/service/SchedulerManager.java
- src/main/java/com/zzarit/oreum/scheduler/service/SyncRunner.java
- src/main/java/com/zzarit/oreum/scheduler/service/SynchronizeService.java
- src/test/java/com/zzarit/oreum/scheduler/client/OpenApiClientTest.java
- src/test/java/com/zzarit/oreum/scheduler/service/MonthlyBatchServiceTest.java
- src/test/java/com/zzarit/oreum/scheduler/service/SynchronizeServiceTest.java
> [feat] daily 데이터베이스 동기화 기능 구현

- src/main/java/com/zzarit/oreum/OreumApplication.java
- src/main/java/com/zzarit/oreum/logging/config/LoggingFilter.java
- src/main/java/com/zzarit/oreum/scheduler/service/MonthlyBatchService.java
- src/main/java/com/zzarit/oreum/scheduler/service/SynchronizeService.java
- src/main/resources/application-prod.yml
> [feat] loggin 설정

- src/main/java/com/zzarit/oreum/place/service/PlaceService.java
- src/main/resources/data.sql
> [fix] null-safe하게 수정

- build.gradle
- src/main/java/com/zzarit/oreum/auth/config/SecurityConfig.java
> [feat] swagger 잠금

- src/main/java/com/zzarit/oreum/folder/service/dto/FolderDetailResponseDto.java
- src/main/java/com/zzarit/oreum/folder/service/dto/FolderResponseDto.java
- src/main/java/com/zzarit/oreum/scheduler/service/SynchronizeService.java
- src/main/resources/data.sql
> [fix] 폴더 조회 로직수정

- src/main/java/com/zzarit/oreum/scheduler/service/SynchronizeService.java
> [fix] 스케줄러 시간대 변경
